### ISSUE TITLE
Confusion with regards to the examples

### ISSUE THREAD

**Issue by dom96** [CORDEA/oauth#16]
I've just had the pleasure to use this wonderful library, and I have some questions regarding the examples.

The examples are awesome but they all seem to use `authorizationCodeGrant`, which launches a kind of hacky http server (why not use asynchttpserver? also, you should never use ``waitFor`` in an async proc!). Is this a common thing to offer to users of an oauth library?

I'm writing my own web app using Jester so I want to cover the callback part myself. I believe I can use ``getAuthorizationCodeGrantUrl`` myself but it would be nice to see the examples do this too.

**Comment by CORDEA** [comment]
Sorry for late response.

> which launches a kind of hacky http server (why not use asynchttpserver? also, you should never use waitFor in an async proc!). Is this a common thing to offer to users of an oauth library?

I think you are right. There is an unreasonable implementation of first release and this should be improved. I will look at other libraries again and consider removing them if it is not common.

> I believe I can use getAuthorizationCodeGrantUrl myself but it would be nice to see the examples do this too.

Yes. I will add a new example instead of `authorizationCodeGrant` examples. Just a moment, please.

**Comment by CORDEA** [comment]
I think that implementation using `getAuthorizationCodeGrantUrl` could be as follows. We can probably write more easily if rethink the oauth library interface...

```diff
diff --git a/examples/slack.nim b/examples/slack.nim
index 72af7b5..ddcb8df 100644
--- a/examples/slack.nim
+++ b/examples/slack.nim
@@ -14,28 +14,52 @@
 # Author: Yoshihiro Tanaka <contact@cordea.jp>
 # date  :2016-03-08
 
+import uri
+import json
 import oauth2
+import strutils
+import sequtils
 import httpclient
-import json
 
 const
     authorizeUrl = "https://slack.com/oauth/authorize"
     accessTokenUrl = "https://slack.com/api/oauth.access"
+    redirectUri = "http://localhost:8080"
+    # Random string
+    state = "aaaaa"
     url = "https://slack.com/api/channels.list"
 
-let html = "resources/index.html".readFile()
-
 echo "Please enter the client id."
 let clientId = readLine(stdin)
 echo "Please enter the client secret."
 let clientSecret = readLine(stdin)
 
+let grantUrl = getAuthorizationCodeGrantUrl(authorizeUrl, clientId, redirectUri, state, @["channels:read"])
 echo "Please go to this url."
+echo grantUrl
+
+# Receive callback url. You can also handle directly from server that was launched.
+echo "Please enter the callback url."
+# ex. https://example.com?code=xxxxxxxxxx&state=xxxxx
+let callbackUrl = readLine(stdin)
+
+let query = parseUri(callbackUrl).query.split("&").mapIt(it.split("="))
+
+var code: string
+var receivedState: string
+for q in query:
+  case q[0]
+  of "code":
+    code = q[1]
+  of "state":
+    receivedState = q[1]
+
+assert state == receivedState
+
 let
-    client = newHttpClient()
-    response = client.authorizationCodeGrant(authorizeUrl, accessTokenUrl,
-        clientId, clientSecret, html, scope = @["channels:read"])
-    obj = parseJson(response.body)
-    accessToken = obj["access_token"].str
-    r = client.getContent(url & "?token=" & accessToken)
+  client = newHttpClient()
+  response = client.getAuthorizationCodeAccessToken(accessTokenUrl, code, clientid, clientSecret, redirectUri)
+  obj = parseJson(response.body)
+  accessToken = obj["access_token"].str
+  r = client.getContent(url & "?token=" & accessToken)
 echo r
```

**Comment by CORDEA** [comment]
`#authorizationCodeGrant` and `#implicitGrant` are now deprecated.  And I've updated docs and examples. Thank you for your advice :)
