### ISSUE TITLE
Insecure generation of `state` values by `generateState` - entropy too low and uses regular PRNG instead of CSPRNG

### ISSUE THREAD

**Issue by rikaardhosein** [CORDEA/oauth#21]
## Overview

Vulnerable code: https://github.com/CORDEA/oauth/blob/b8c163b0d9cfad6d29ce8c1fb394e5f47182ee1c/src/oauth2.nim#L179

The `state` values generated by the `generateState` function do not have sufficient entropy. These can be successfully guessed by an attacker allowing them to perform a CSRF vs a user, associating the user's session with the attacker's protected resources.

## Details

```nim
proc generateState*(): string =
    ## Generate a state.
    var r = 0
    result = ""
    randomize()
    for i in 0..4:
        r = rand(25)
        result = result & chr(97 + r)
```

There are only 25^4 possible `state` values.
That works out to log_2(25^4) = 18.57 bits of entropy.

The `state` value is meant to be generated and consumed by the client application that initiated the oauth2 authorization process and is not intended for usage by human users.

In [RFC6819](https://www.rfc-editor.org/rfc/rfc6819), in section __[5.1.4.2.2 Use High Entropy for Secrets](https://www.rfc-editor.org/rfc/rfc6819#section-5.1.4.2.2)__, it states

>  When creating secrets not intended for usage by human users (e.g.,
   client secrets or token handles), the authorization server should
   include a reasonable level of entropy in order to mitigate the risk
   of guessing attacks.  The token value should be >=128 bits long and
   constructed from a cryptographically strong random or pseudo-random
   number sequence (see [RFC4086](Randomness Requirements for Security") for best current practice) generated
   by the authorization server.

The 18.57 bits of entropy provided are much less than the recommended minimum of 128.

It also uses `std/random`'s `rand` function. The documentation for `std/random` states:

> **Do not use this module for cryptographic purposes!**

While `state` isn't exactly a cryptographic value, it __should__ be generated in a cryptographically secure way. `generateState` should be using a CSPRNG.

## Recommendation

Modify the `generateState` function to generate `state` values of at least 128 bits of entropy while using a CSPRNG.

**Comment by CORDEA** [comment]
Hi, thank you so much for reporting.
As far as I could find out, `std/sysrand` can be used for generating state using CSPRNG. Anyway, I'm gonna figure it out.

**Comment by rikaardhosein** [comment]
Thank you for the fixes!

Would you be ok with creating security advisories (within Github) for issues #21 and #22 and also requesting CVEs for them?

**Comment by CORDEA** [comment]
Of course, thank you for your support!

**Comment by rikaardhosein** [comment]
I think Github will let me submit vulnerabilities through the Security tab for this repository now. I'll submit two vulnerabilities through that process. That might make things a bit easier for you.

Thanks again for the quick fixes and being so responsive!
