### ISSUE TITLE
Encoding URL base string on MediaWiki

### ISSUE THREAD

**Issue by greencardamom** [CORDEA/oauth#4]
When using the library on MediaWiki with this URL https://en.wikipedia.org/w/index.php?title=Special:OAuth/identify the signature does not work it returns "Invalid signature". The Nim library generates a signature string that ends with "title%3DSpecial%3AOAuth%2Fidentify" .. however to get it to work on MediaWiki the signature should end as "title%3DSpecial%253AOAuth%252Fidentify" which is to say the ":" and "/" in the query portion are urlencoded twice (":" -> "%3A" -> "%253A").  I don't know why this is, but it works. I don't know if this is OAuth specifications, a bug in MediaWiki or a bug in the Nim oauth library. It was a hard bug to discover so want to report it in case anyone else uses the library with MediaWiki.

**Comment by CORDEA** [comment]
Thank you for reporting :)
I was thinking about this problem, but it will take a little more time...

**Comment by CORDEA** [comment]
Reserved characters (":", "/" ...) of the query needs to be percent encoded, but it is not "MUST" in RFC 3986. Expected value may change with service.

I think that the encoding of the query part should be done on the application side, not on the library. 

I'm considering adding examples like requests-oauthlib :)

- http://requests-oauthlib.readthedocs.io/en/latest/examples/mediawiki.html
