### ISSUE TITLE
Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by lbcheng888** [CORDEA/oauth#7]
followed the url after "Please go to this url."
The redirect URI in the request, http://localhost:8080, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/114704182264908205920?project=777725626149

**Comment by CORDEA** [comment]
Hi, thanks for reporting :)

Maybe, the redirect uri that you entered to console of google cloud platform is not "http://localhost". Easiest way to solve this, select "other" application type when create OAuth client id.

If you want to select the Web application type, you need to enter the correct redirect uri (http://localhost) and remove `refreshToken = obj["refresh_token"].str` line from `examples/gmail.nim`. Bacause, as far as I tried, refresh token will not return in Web application type.

Please reopen if you find any additional problem.
